version: "3.9"
services:
  app:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
        - config-data:/config:Z
        - gallery-data:/gallery:Z
    ports:
      - 8000:80
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        - mysql-data:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe123!
      MYSQL_DATABASE: archivedb
  adminer:
    image: adminer
    #restart: always
    ports:
      - 8080:8080
volumes:
  mysql-data:
  gallery-data:
  config-data:
